import React from 'react'
import './globals.scss'
import { Inter } from 'next/font/google'
import Header from '@/components/Header/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Good Dev Hunting',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}): JSX.Element {
  return (
      <html lang="en">
      <body>
      <Header />
      {children}
      </body>
      </html>
  )
}
