import React from 'react'

export const ProfileData = [
  {
    id: 1,
    name: 'Karolina Morwińska',
    seniority: 'Senior Fullstack Developer',
    location: 'Poland, Warsaw / Remote',
    technology: 'Javascript',
    technology2: 'React.js',
    technology3: 'Vue.js',
    others: '+5 more',
  },
  {
    id: 2,
    name: 'Robert Fox',
    seniority: 'Intern Frontend Developer',
    location: 'Italy, Rome / Remote',
    technology: 'Javascript',
    technology2: 'React.js',
    technology3: 'Vue.js',
    others: '+5 more',
  },
  {
    id: 3,
    name: 'Kristin Watson',
    seniority: 'Junior Frontend Developer',
    location: 'Poland, Warsaw / Remote',
    technology: 'Javascript',
    technology2: 'React.js',
    technology3: 'Vue.js',
    others: '+5 more',
  },
  {
    id: 4,
    name: 'Veres Panna',
    seniority: 'Mid Fullstack Developer',
    location: 'Poland, Warsaw / Remote',
    technology: 'Javascript',
    technology2: 'React.js',
    technology3: 'Vue.js',
    others: '+5 more',
  },
  {
    id: 5,
    name: 'Albert Flores',
    seniority: 'Senior Backend Developer',
    location: 'Poland, Warsaw / Remote',
    technology: 'Javascript',
    technology2: 'React.js',
    technology3: 'Vue.js',
    others: '+5 more',
  },
  {
    id: 6,
    name: 'Robert Fox',
    seniority: 'Intern Frontend Developer',
    location: 'Italy, Rome / Remote',
    technology: 'Javascript',
    technology2: 'React.js',
    technology3: 'Vue.js',
    others: '+5 more',
  },
]
